// Full UI + genuine gameplay/crypto. By default only the opaque relay hop is
// substituted; SPACE_MAN_RELAY_HOST opts into the actual public relay.
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),path=require('node:path'),fs=require('node:fs/promises');
const {chromium,webkit}=require('playwright'),{simulatedRelay,validateRelayHost}=require('./arena-network-helper.cjs');
const ROOT=path.resolve(__dirname,'../..'),live=!!process.env.SPACE_MAN_RELAY_HOST,engine=process.env.SPACE_MAN_JOURNEY_BROWSER==='webkit'?webkit:chromium;
const relayHost=process.env.SPACE_MAN_RELAY_HOST||'relay.test';if(live)validateRelayHost(relayHost);
async function launch(t){
 let server,browser;const peers=[],hub=live?null:require('../harness.cjs').relay();
 let base=process.env.SPACE_MAN_BASE_URL;
 if(!base){server=http.createServer(async(req,res)=>{const p=path.resolve(ROOT,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname)+(req.url.endsWith('/')?'index.html':''));if(!p.startsWith(ROOT+path.sep))return res.writeHead(400).end();try{const b=await fs.readFile(p);res.writeHead(200,{'content-type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(p)]||'application/octet-stream','cache-control':'no-store'}).end(b);}catch(_){res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port+'/';}
 browser=await engine.launch(engine===chromium&&process.env.SPACE_MAN_CHROMIUM_PATH?{executablePath:process.env.SPACE_MAN_CHROMIUM_PATH}:{});
 t.after(async()=>{for(const c of peers)await c.page.evaluate(()=>{clearInterval(window.driver);SpaceManNet.leave();}).catch(()=>{});await browser.close();if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}for(const c of peers)assert.deepEqual(c.errors,[],c.name+' has no uncaught errors');});
 async function peer(name,device={}){
  const context=await browser.newContext({viewport:{width:1280,height:800},serviceWorkers:'block',...device});const c={name,context,errors:[],sockets:0,unexpectedSockets:0,deliveryErrors:0,sent:0,received:0,encryptedSent:0,encryptedReceived:0,sentTypes:{},receivedTypes:{},offline:false};peers.push(c);
  if(!live)await simulatedRelay(context,c,hub);
  await context.addInitScript(host=>{const p=/^\/pr\/([1-9]\d*)\/([a-f0-9]{40})\/([a-f0-9]{40})\//.exec(location.pathname),prefix=p?'sm2.preview.'+p[1]+'.'+p[2]+'.'+p[3]+'.':'';localStorage.setItem(prefix+'sm2.settings',JSON.stringify({netRelay:host==='default'?'':host,music:false,sfx:false,muted:true,haptics:false,reduceMotion:true}));window.testPad={connected:true,mapping:'standard',index:0,axes:[0,0],buttons:Array.from({length:17},()=>({pressed:false,value:0}))};Object.defineProperty(navigator,'getGamepads',{value:()=>[window.testPad],configurable:true});},relayHost);
  c.page=await context.newPage();c.page.setDefaultTimeout(30000);c.page.on('pageerror',e=>c.errors.push(e.message));c.page.on('dialog',d=>d.accept());if(live)c.page.on('websocket',ws=>{c.sockets++;ws.on('framesent',e=>{if(Buffer.from(e.payload)[0]===4)c.encryptedSent++;});ws.on('framereceived',e=>{if(Buffer.from(e.payload)[0]===5)c.encryptedReceived++;});});await c.page.goto(base);if(process.env.SPACE_MAN_EXPECTED_SHA)assert.equal(JSON.parse(await c.page.locator('meta[name="space-man-preview"]').getAttribute('content')).sha,process.env.SPACE_MAN_EXPECTED_SHA);return c;
 }
 return{peer,peers};
}
async function driver(p){await p.evaluate(()=>{window.visited=[];window.driver=setInterval(()=>{const j=journeyUI?.room.current;if(!j)return;if(!visited.includes(j.index))visited.push(j.index);testPad.axes=[0,0];testPad.buttons.forEach(b=>b.pressed=false);if(j.phase!=='running')return;if(j.mode==='runner'){testPad.axes[0]=1;}else if(j.mode==='arena'){testPad.axes[0]=1;testPad.buttons[2].pressed=true;}else{const s=raceUI?.snapshot(),a=s?.actors.find(a=>a.controller==='human');if(s&&a&&s.phase==='racing'){const cmd=SpaceManRace.cpuInput(s,a);testPad.axes[0]=cmd.steer;testPad.buttons[0].pressed=cmd.boost;testPad.buttons[1].pressed=cmd.brake;}}},16);});}
async function capture(p,name){if(!process.env.SPACE_MAN_JOURNEY_SCREENSHOTS)return;await fs.mkdir(process.env.SPACE_MAN_JOURNEY_SCREENSHOTS,{recursive:true});await p.screenshot({path:path.join(process.env.SPACE_MAN_JOURNEY_SCREENSHOTS,name+'.png'),animations:'disabled'});}
const state=p=>p.evaluate(()=>{const s=journeyUI.room.status();return{mode:s.journey?.mode,index:s.journey?.index,epoch:s.journey?.epoch,phase:s.journey?.phase,p:SpaceManNet.info().myP,room:SpaceManNet.info().roomId,role:SpaceManNet.info().role,effectiveRole:s.info.role,players:s.info.players,spectators:s.info.spectators};});
test((live?'LIVE public':'simulated')+' relay: one crew through all engines and a boss, late watch, queued seat, reconnect and exit',{timeout:420000},async t=>{
 const{peer}=await launch(t),host=await peer('host'),friend=await peer('phone',{viewport:{width:390,height:844},isMobile:true,hasTouch:true}),watcher=await peer('watcher');
 await host.page.locator('#btnExpeditionFriends').click();await host.page.locator('#journeyHost').click();await host.page.waitForFunction(()=>journeyUI?.room.active);const invite=await host.page.evaluate(()=>SpaceManNet.info().link);
 for(const[c,watch]of[[friend,false],[watcher,true]]){await c.page.locator('#btnExpeditionFriends').click();await c.page.locator('#journeyJoinInput').fill(invite);await c.page.locator(watch?'#journeyWatch':'#journeyJoin').click();await c.page.waitForFunction(()=>journeyUI?.room.active&&SpaceManNet.roster().some(r=>r.you));}
 await host.page.waitForFunction(()=>SpaceManNet.roster().length===3);const initial=await Promise.all([host,friend,watcher].map(c=>state(c.page)));
 await host.page.locator('#journeyStart').click();await Promise.all([host,friend,watcher].map(c=>c.page.waitForFunction(()=>journeyUI.room.current?.phase==='running')));
 assert.equal((await state(watcher.page)).role,1);assert.equal(await host.page.locator('#btnExpeditionContinue').count(),0);await capture(friend.page,'journey-phone-first');await host.page.keyboard.press('Escape');await host.page.waitForFunction(()=>journeyUI.room.current?.phase==='paused');
 // A real socket interruption; session key and role must recover without a new room.
 const key=await friend.page.evaluate(()=>SpaceManNet._n1.bytes.hex(SpaceManNet._n1.session().keys.pub));await friend.page.evaluate(()=>SpaceManNet._n1.session().relay.kick('acceptance socket interruption'));
 await friend.page.waitForFunction(()=>SpaceManNet._n1.session()?.relay.state==='established');assert.equal(await friend.page.evaluate(()=>SpaceManNet._n1.bytes.hex(SpaceManNet._n1.session().keys.pub)),key);
 const late=await peer('late viewer',{viewport:{width:320,height:568},isMobile:true,hasTouch:true});await late.page.locator('#btnExpeditionFriends').click();await late.page.locator('#journeyJoinInput').fill(invite);await late.page.locator('#journeyJoin').click();await late.page.waitForFunction(()=>journeyUI.room.active&&SpaceManNet.roster().some(r=>r.you)&&journeyUI.room.current?.phase==='paused');assert.equal((await state(late.page)).role,1);const lateMode=(await state(late.page)).mode;const crew=late.page.locator(lateMode==='runner'?'#btnJourneyCrew':lateMode==='arena'?'#arenaJourneyCrew':'#raceJourneyCrew');if(!await crew.isVisible())await late.page.keyboard.press('Escape');await crew.click();await late.page.locator('#journeyRole').click();await late.page.locator('#journeyResume').click();const hostMode=(await state(host.page)).mode;await host.page.locator(hostMode==='runner'?'#btnResume':hostMode==='arena'?'#arenaResume':'#raceResume').click();await late.page.waitForFunction(()=>journeyUI.room.current?.phase==='running');const resume=late.page.locator(lateMode==='runner'?'#btnResume':lateMode==='arena'?'#arenaResume':'#raceResume');if(await resume.isVisible()&&await resume.isEnabled())await resume.click();await driver(host.page);await driver(friend.page);await driver(late.page);
 for(let index=1;index<=5;index++){
  await host.page.waitForFunction(n=>journeyUI.room.current?.index>=n,index,{timeout:115000});await friend.page.waitForFunction(n=>journeyUI.room.current?.index>=n,index,{timeout:15000});await watcher.page.waitForFunction(n=>journeyUI.room.current?.index>=n,index,{timeout:15000});
  const states=await Promise.all([host,friend,watcher].map(c=>state(c.page)));states.forEach((s,i)=>{assert.equal(s.room,initial[i].room);assert.equal(s.p,initial[i].p);assert.equal(s.role,initial[i].role);});
  if(index===4){await host.page.waitForFunction(()=>journeyUI.room.current?.phase==='running');assert.equal(await host.page.evaluate(()=>arenaUI.snapshot().actors.length),5);await late.page.waitForFunction(()=>journeyUI.room.current?.index===4&&arenaUI?.snapshot()?.actors.some(a=>a.boss));for(const phase of['charging','active','recover']){await late.page.waitForFunction(phase=>arenaUI?.snapshot()?.actors.some(a=>a.boss?.phase===phase),phase,{timeout:20000});await capture(late.page,'journey-phone-boss-'+phase);}}
 }
 assert.equal((await state(late.page)).role,0,'late viewer takes requested seat at next boundary');
 for(const c of[host,friend,watcher])assert.ok(c.encryptedSent>0&&c.encryptedReceived>0,'genuine encrypted relay traffic');
 await host.page.waitForFunction(()=>journeyUI.room.current?.phase==='running');await host.page.keyboard.press('Escape');const exitMode=(await state(host.page)).mode;await host.page.locator(exitMode==='runner'?'#btnJourneyCrew':exitMode==='arena'?'#arenaJourneyCrew':'#raceJourneyCrew').click();await host.page.locator('#journeyLeave').click();await Promise.all([friend,watcher,late].map(c=>c.page.waitForFunction(()=>!SpaceManNet.active&&!sharedEncounter&&!arenaUI?.active&&!raceUI?.active)));assert.equal(await host.page.locator('#ovAttract').evaluate(el=>el.inert),false);
});
