const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs/promises'),path=require('node:path');
const {chromium,webkit}=require('playwright'),ROOT=path.resolve(__dirname,'../..'),engine=process.env.SPACE_MAN_IDENTITY_BROWSER==='webkit'?webkit:chromium;
for(const [width,height]of[[320,568],[390,844],[844,390],[1280,800]])test(`runner YOU marker keeps equipped suit at ${width}x${height}`,{timeout:25000},async t=>{
 let browser;const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost'),p=path.resolve(ROOT,'.'+decodeURIComponent(u.pathname)+(u.pathname.endsWith('/')?'index.html':''));if(!p.startsWith(ROOT+path.sep))return res.writeHead(400).end();res.writeHead(200,{'content-type':({'.html':'text/html','.js':'text/javascript','.css':'text/css'})[path.extname(p)]||'application/octet-stream'}).end(await fs.readFile(p));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{await browser?.close();server.closeAllConnections();await new Promise(r=>server.close(r));});
 browser=await engine.launch();const page=await browser.newPage({viewport:{width,height},isMobile:width<600,hasTouch:true,serviceWorkers:'block'}),errors=[];page.on('pageerror',e=>errors.push(e.message));t.after(()=>assert.deepEqual(errors,[]));await page.goto(process.env.SPACE_MAN_BASE_URL||`http://127.0.0.1:${server.address().port}/`);
 await page.evaluate(()=>{settings.muted=true;settings.reduceMotion=true;settings.autorun=false;Object.assign(G.cosmetics,{suit:'mint',helmet:'bubble',eyes:'happy',hat:'antenna'});window.runnerMarkers=[];const badge=SpaceManArt.identityBadge;SpaceManArt.identityBadge=function(...a){runnerMarkers.push({text:a[1],x:a[2],y:a[3],w:a[4]});if(runnerMarkers.length>20)runnerMarkers.shift();return badge.apply(this,a);};});
 await page.locator('#btnPlay').click();await page.waitForFunction(()=>runnerMarkers.some(p=>p.text==='YOU'));
 const b=await page.evaluate(()=>runnerMarkers.at(-1));const floor=await page.evaluate(()=>(12+viewInset('top')+(G.mission?79:55)*uiScale())*view.scale/view.dpr+8);assert.ok(b.y>=floor,'marker clears the scaled runner mission HUD');assert.equal(b.text,'YOU');assert.ok(b.x>=0&&b.x+b.w<=width&&b.y>=0&&b.y<height);assert.equal(await page.evaluate(()=>G.cosmetics.suit),'mint');
 if(process.env.SPACE_MAN_IDENTITY_SCREENSHOTS){await fs.mkdir(process.env.SPACE_MAN_IDENTITY_SCREENSHOTS,{recursive:true});await page.screenshot({path:path.join(process.env.SPACE_MAN_IDENTITY_SCREENSHOTS,`runner-identity-${width}.png`)});}
});
