const test=require('node:test'),assert=require('node:assert/strict');
const{client,relay,until}=require('./harness.cjs');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function setup(t,seed=2){const hub=relay(),all=[];function peer(){const c=client(hub,{game:false});all.push(c);c.run(`window.seen=[];window.room=SpaceManJourneyRoom.create({net:SpaceManNet,hostOptions:()=>({relayHost:'relay.test'}),onEncounter:leg=>seen.push(leg.index)});`);c.room=c.context.room;return c;}t.after(()=>all.forEach(c=>{c.room.leave();c.close();}));const host=peer();assert.equal(await host.room.hosting(seed),true);async function join(role=0){const c=peer();assert.equal(await c.room.join(host.net.info().link,role),true);await until(()=>c.room.current&&c.net.roster().some(r=>r.you));return c;}async function advance(ms){for(let i=0;i<ms;i+=100){hub.advance(100);await delay(18);}}return{hub,host,join,advance};}
test('shared coordinator prepares once per epoch, carries watchers, attaches UI late and exits everyone',async t=>{const{host,join,advance}=await setup(t),guest=await join(),watch=await join(1);assert.equal(host.room.start(),true);await until(()=>guest.room.current?.phase==='barrier');await advance(1200);await until(()=>guest.room.current?.phase==='running');assert.equal(host.context.seen.length,1);assert.equal(guest.context.seen.length,1);assert.equal(watch.context.seen.length,1);assert.equal(watch.room.status().info.role,1);const before=host.net.info().roomId;let changes=0;const off=guest.room.adapter.attach({onChange(){changes++;}});assert.ok(changes>0);off();const late=await join();assert.equal(late.net.info().role,1);assert.equal(host.net.info().roomId,before);host.room.leave();await until(()=>!guest.room.active&&!watch.room.active&&!late.room.active,'host closure');assert.equal(host.net.active,false);});
test('runner facade sends epoch presence, finishes locally into watching, and ignores standalone start/kill controls',async t=>{const{host,join,advance}=await setup(t),guest=await join();host.room.start();await until(()=>guest.room.current?.phase==='barrier');await advance(1200);await until(()=>guest.room.current?.phase==='running');assert.equal(guest.room.current.mode,'runner');const n=guest.room.runnerNet;n.sendPresence(123,45,0,8,0,11,20,1,0);await advance(200);await until(()=>host.room.runnerNet.presence().some(p=>p.p===guest.net.info().myP));assert.equal(n.startRound(),false);assert.equal(n.kill(),false);guest.room.runnerDone({x:123,y:45,vx:0,vy:0,state:8,chain:0,score:11,dist:20,frame:2});assert.equal(guest.room.status().info.role,1);assert.equal(guest.net.info().role,0,'effective watching preserves the stable player role');});
test('runner facade never treats a queued spectator seat request as admission',async t=>{const{host,join,advance}=await setup(t),watch=await join(1);host.room.start();await until(()=>watch.room.current?.phase==='barrier');await advance(1200);await until(()=>watch.room.current?.phase==='running');assert.equal(await watch.room.runnerNet.setRole(0),false,'legacy runner may only restart after confirmed current admission');assert.equal(watch.room.status().pendingRole,0);assert.equal(watch.net.info().role,1);assert.equal(watch.room.status().info.role,1);});
test('host opening Crew during a barrier pauses the first live frame without ending the session',async t=>{const{host,join,advance}=await setup(t),guest=await join();host.room.start();await until(()=>guest.room.current?.phase==='barrier');host.room.adapter.openCrew();await advance(1200);await until(()=>guest.room.current?.phase==='paused');assert.equal(host.room.active,true);const epoch=host.room.current.epoch,tick=host.room.current.tick;await advance(500);assert.equal(host.room.current.epoch,epoch);assert.equal(host.room.current.tick,tick);assert.equal(host.room.pause(false),true);await advance(100);await until(()=>guest.room.current?.phase==='running');assert.equal(host.room.current.epoch,epoch);});
test('runner Pause during readiness is remembered at launch and can resume the same epoch',async t=>{const{host,advance}=await setup(t);host.room.start();assert.equal(host.room.pause(true),true);await advance(1200);assert.equal(host.room.current.phase,'paused');assert.equal(host.room.current.tick,0);assert.equal(host.room.pause(false),true);await advance(100);assert.equal(host.room.current.phase,'running');assert.ok(host.room.current.tick>0);});


test('shared race adapter exposes acknowledged Item readiness for host and guest without giving watchers control',async t=>{
 const{host,join,advance}=await setup(t,6),guest=await join(),watch=await join(1);
 assert.equal(host.room.adapter.itemReady(),false);host.room.start();
 await until(()=>guest.room.current?.phase==='barrier');await advance(5000);
 await until(()=>guest.room.current?.engine?.state.phase==='racing');
 host.room.adapter.step({});guest.room.adapter.step({});await advance(150);
 await until(()=>host.room.adapter.itemReady()&&guest.room.adapter.itemReady(),'acknowledged neutral Item baseline');
 assert.equal(host.room.adapter.itemReady(),true);assert.equal(guest.room.adapter.itemReady(),true);assert.equal(watch.room.adapter.itemReady(),false);
 host.room.adapter.release();guest.room.adapter.release();
 assert.equal(host.room.adapter.itemReady(),false);assert.equal(guest.room.adapter.itemReady(),false);
 host.room.adapter.step({});guest.room.adapter.step({});await advance(150);
 await until(()=>host.room.adapter.itemReady()&&guest.room.adapter.itemReady(),'acknowledged neutral Item baseline');
 assert.equal(host.room.adapter.itemReady(),true);assert.equal(guest.room.adapter.itemReady(),true);
 host.room.pause(true);assert.equal(host.room.adapter.itemReady(),false);await until(()=>guest.room.current.phase==='paused');assert.equal(guest.room.adapter.itemReady(),false);
});
