#!/usr/bin/env node
'use strict';

// Run only from the trusted default-branch checkout. PR files are data here;
// their offline tests run on separate, read-only runners before assembly.
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const REPOSITORY = 'picatz/space-man';
const AUTHOR = 'picatz';
const BRANCH = 'main';
const SHA = /^[a-f0-9]{40}$/;
const SITE_BYTES_LIMIT = 200 * 1024 * 1024;
const INDEX_BYTES_RESERVE = 1024 * 1024;

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

function validNumber(number) {
  return Number.isSafeInteger(number) && number > 0;
}

function trustedPull(pull) {
  return pull?.state === 'open' && validNumber(pull.number) &&
    pull.user?.login === AUTHOR && pull.base?.repo?.full_name === REPOSITORY &&
    pull.base.ref === BRANCH && pull.head?.repo?.full_name === REPOSITORY &&
    SHA.test(pull.head.sha);
}

function entry(number, sha) {
  return { number, sha, label: number === 0 ? 'main' : `pr-${number}` };
}

function makePlan(mainSha, pulls) {
  assert(SHA.test(mainSha), 'Invalid main SHA');
  const previews = pulls.filter(trustedPull)
    .map(pull => entry(pull.number, pull.head.sha)).sort((a, b) => a.number - b.number);
  assert(new Set(previews.map(item => item.number)).size === previews.length, 'Duplicate PR number');
  assert(previews.length < 256, 'Too many trusted PRs for one Actions matrix');
  return { version: 1, repository: REPOSITORY, main: entry(0, mainSha), previews };
}

function validatePlan(plan) {
  assert(plan?.version === 1 && plan.repository === REPOSITORY, 'Invalid preview plan');
  assert(plan.main?.number === 0 && plan.main.label === 'main' && SHA.test(plan.main.sha), 'Invalid production entry');
  assert(Array.isArray(plan.previews) && plan.previews.length < 256, 'Invalid preview list');
  for (const item of plan.previews) {
    assert(validNumber(item.number) && SHA.test(item.sha) && item.label === `pr-${item.number}`, 'Invalid preview entry');
  }
  assert(new Set(plan.previews.map(item => item.number)).size === plan.previews.length, 'Duplicate PR number');
  return plan;
}

function testJobName(item) {
  return `Offline checks ${item.label} ${item.sha}`;
}

function successfulTest(item, jobs) {
  const matching = jobs.filter(job => job.name === testJobName(item));
  // Never accept a matching name from another run, attempt, PR, or SHA. The API
  // caller below restricts run/attempt; job names are generated by trusted YAML.
  return matching.length === 1 && matching[0].status === 'completed' &&
    matching[0].conclusion === 'success';
}

function selectPublishable(plan, currentMainSha, pulls, jobs) {
  validatePlan(plan);
  assert(currentMainSha === plan.main.sha, 'Main changed during testing; wait for the queued reconcile run');
  assert(successfulTest(plan.main, jobs), 'Production offline tests did not pass; preserving the deployed site');
  const current = new Map(pulls.filter(trustedPull).map(pull => [pull.number, pull.head.sha]));
  const included = [], omitted = [];
  for (const item of plan.previews) {
    if (current.get(item.number) !== item.sha) omitted.push({ ...item, reason: 'closed, changed, or no longer eligible' });
    else if (!successfulTest(item, jobs)) omitted.push({ ...item, reason: 'exact-head offline tests did not pass' });
    else included.push(item);
  }
  return { included, omitted };
}

function createApi(token, fetchImpl = fetch) {
  assert(token, 'GITHUB_TOKEN is required');
  return async function api(route) {
    assert(route.startsWith(`/repos/${REPOSITORY}/`), 'Unexpected API route');
    const response = await fetchImpl(`https://api.github.com${route}`, {
      headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28' },
      redirect: 'error', signal: AbortSignal.timeout(30000),
    });
    assert(response.ok, `GitHub API failed (${response.status}): ${route}`);
    return response.json();
  };
}

async function allPages(api, route, key) {
  const results = [];
  for (let page = 1; ; page++) {
    const body = await api(`${route}${route.includes('?') ? '&' : '?'}per_page=100&page=${page}`);
    const items = key ? body[key] : body;
    assert(Array.isArray(items), 'Unexpected paginated API response');
    results.push(...items);
    if (items.length < 100) return results;
  }
}

async function currentState(api) {
  const [ref, pulls] = await Promise.all([
    api(`/repos/${REPOSITORY}/git/ref/heads/${BRANCH}`),
    allPages(api, `/repos/${REPOSITORY}/pulls?state=open&base=${BRANCH}`),
  ]);
  assert(SHA.test(ref?.object?.sha), 'Invalid current main SHA');
  return { mainSha: ref.object.sha, pulls };
}

function output(name, value) {
  assert(process.env.GITHUB_OUTPUT, 'GITHUB_OUTPUT is required');
  const encoded = typeof value === 'string' ? value : JSON.stringify(value);
  assert(!/[\r\n]/.test(encoded), 'Unexpected multiline output');
  fs.appendFileSync(process.env.GITHUB_OUTPUT, `${name}=${encoded}\n`);
}

function gitEnvironment(environment = process.env) {
  const clean = Object.fromEntries(Object.entries(environment).filter(([key]) =>
    !key.startsWith('GIT_') && key !== 'GITHUB_TOKEN' && key !== 'GH_TOKEN'));
  return { ...clean, GIT_CONFIG_NOSYSTEM: '1', GIT_CONFIG_SYSTEM: '/dev/null',
    GIT_CONFIG_GLOBAL: '/dev/null', GIT_ATTR_NOSYSTEM: '1',
    GIT_TERMINAL_PROMPT: '0', GIT_LFS_SKIP_SMUDGE: '1' };
}

function git(args, cwd) {
  return execFileSync('git', ['-c', 'core.hooksPath=/dev/null',
    '-c', 'core.fsmonitor=false', '-c', 'core.attributesFile=/dev/null',
    '-c', 'filter.lfs.process=', '-c', 'filter.lfs.smudge=', '-c', 'filter.lfs.required=false',
    '-c', 'protocol.file.allow=never', ...args], {
    cwd, env: gitEnvironment(), encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], timeout: 120000,
  }).trim();
}

function directoryBytes(directory) {
  const stat = fs.lstatSync(directory);
  assert(stat.isDirectory() && !stat.isSymbolicLink(), 'Static output must be a real directory');
  let bytes = 0;
  for (const name of fs.readdirSync(directory)) {
    const file = path.join(directory, name), info = fs.lstatSync(file);
    assert(!info.isSymbolicLink(), 'Static output cannot contain symlinks');
    if (info.isDirectory()) bytes += directoryBytes(file);
    else {
      assert(info.isFile() && info.nlink === 1, 'Static output must contain regular, non-hardlinked files');
      bytes += info.size;
    }
  }
  return bytes;
}

function checkoutSource(sha, directory) {
  assert(SHA.test(sha), 'Invalid checkout SHA');
  fs.mkdirSync(directory, { recursive: true });
  git(['init', '--quiet'], directory);
  // Public same-repository commits only. No PR-controlled remotes, credentials,
  // submodules, hooks, package installation, or PR build scripts are used.
  git(['fetch', '--quiet', '--depth=1', '--no-tags', `https://github.com/${REPOSITORY}.git`, sha], directory);
  git(['checkout', '--quiet', '--detach', '--force', 'FETCH_HEAD'], directory);
  assert(git(['rev-parse', 'HEAD'], directory) === sha, 'Source checkout SHA mismatch');
  return directory;
}

function siteBase(trustedSource) {
  const domain = fs.readFileSync(path.join(trustedSource, 'CNAME'), 'utf8').trim();
  assert(/^(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,}$/i.test(domain), 'Invalid trusted CNAME');
  return `https://${domain}/`;
}

function writeIndex(outputDir, mainSha, published, omitted, base) {
  const directory = path.join(outputDir, 'pr');
  fs.mkdirSync(directory, { recursive: true });
  const manifest = { version: 1, production: { sha: mainSha, url: base },
    previews: published.map(item => ({ number: item.number, sha: item.sha,
      buildSha: mainSha, url: `${base}pr/${item.number}/${item.sha}/${mainSha}/` })), omitted };
  fs.writeFileSync(path.join(directory, 'previews.json'), JSON.stringify(manifest, null, 2) + '\n');
  const rows = manifest.previews.map(item =>
    `<li><a href="./${item.number}/${item.sha}/${mainSha}/">PR #${item.number}</a> <code>${item.sha}</code></li>`).join('\n');
  fs.writeFileSync(path.join(directory, 'index.html'), `<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex,nofollow"><title>Space Man PR previews</title>
<style>body{font:16px system-ui;max-width:65rem;margin:3rem auto;padding:0 1rem;background:#090c20;color:#e8f1ff}a{color:#8ce9ff}li{margin:1rem 0}code{overflow-wrap:anywhere}</style>
<h1>Space Man PR previews</h1><p><a href="../">Production game</a></p>
<p>Current passing, picatz-authored, same-repository PR heads. These are development builds on the production origin.</p>
<ul>${rows || '<li>No eligible passing previews in this publication.</li>'}</ul>
<p>Links identify one full source commit and trusted builder revision. Superseded, closed, failed, or incompatible previews expire at the next publication. These are not permanent archives.</p></html>\n`);
  return manifest;
}

async function assemble(plan, selection, options = {}) {
  validatePlan(plan);
  const trusted = options.trusted || path.resolve(__dirname, '..');
  const outputDir = path.resolve(options.output || process.env.PAGES_OUTPUT || '_site');
  assert(outputDir !== trusted && !trusted.startsWith(outputDir + path.sep), 'Unsafe output directory');
  assert(!fs.existsSync(outputDir) || fs.readdirSync(outputDir).length === 0, 'Output directory must be empty');
  const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'space-man-previews-'));
  const builder = path.join(trusted, 'scripts', 'build-preview.cjs');
  const copyProduction = options.copyProduction || require(builder).copyProduction;
  const checkout = options.checkout || checkoutSource;
  const build = options.build || ((source, destination, item) => {
    execFileSync(process.execPath, [builder, '--source', source, '--output', destination,
      '--pr', String(item.number), '--sha', item.sha, '--build-sha', plan.main.sha], { stdio: 'pipe', timeout: 120000 });
  });
  const published = [], omitted = [...selection.omitted];
  const byteLimit = options.byteLimit || SITE_BYTES_LIMIT;
  try {
    await copyProduction(trusted, outputDir);
    let siteBytes = directoryBytes(outputDir);
    assert(siteBytes + INDEX_BYTES_RESERVE <= byteLimit, 'Production exceeds the site byte budget');
    for (const item of selection.included) {
      try {
        const source = await checkout(item.sha, path.join(temporary, `source-${item.number}`));
        const built = path.join(temporary, `built-${item.number}`);
        await build(source, built, item);
        const previewBytes = directoryBytes(built);
        assert(siteBytes + previewBytes + INDEX_BYTES_RESERVE <= byteLimit, 'Aggregate site byte budget exceeded');
        const target = path.join(outputDir, 'pr', String(item.number), item.sha, plan.main.sha);
        fs.mkdirSync(path.dirname(target), { recursive: true });
        fs.cpSync(built, target, { recursive: true, errorOnExist: true, force: false });
        siteBytes += previewBytes;
        published.push(item);
      } catch (error) {
        fs.rmSync(path.join(outputDir, 'pr', String(item.number)), { recursive: true, force: true });
        // Failures in one preview must not hold production/other PRs hostage.
        omitted.push({ ...item, reason: 'preview source or static build unavailable' });
        console.warn(`::warning::PR #${item.number} ${item.sha} omitted: ${String(error.message).split('\n')[0]}`);
      }
    }
    fs.writeFileSync(path.join(outputDir, '.nojekyll'), '');
    const manifest = writeIndex(outputDir, plan.main.sha, published, omitted, options.base || siteBase(trusted));
    assert(directoryBytes(outputDir) <= byteLimit, 'Complete site exceeds the byte budget');
    return manifest;
  } finally {
    fs.rmSync(temporary, { recursive: true, force: true });
  }
}

function writeSummary(manifest) {
  if (!process.env.GITHUB_STEP_SUMMARY) return;
  let summary = `## Prepared Pages site\n\nProduction source: \`${manifest.production.sha}\`\n\n` +
    'These links go live only after the deployment job succeeds.\n\n';
  for (const item of manifest.previews) summary += `- [PR #${item.number}](${item.url}) — \`${item.sha}\`\n`;
  if (!manifest.previews.length) summary += 'No passing eligible previews.\n';
  for (const item of manifest.omitted) summary += `- Omitted PR #${item.number}: ${item.reason}\n`;
  summary += '\nSuperseded/closed/failed previews may expire on the next publication. No permanent archive is promised.\n';
  fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, summary);
}

async function main(command) {
  assert(process.env.SPACE_MAN_PREVIEWS_ENABLED === 'true', 'Pages previews are disabled');
  assert(process.env.GITHUB_REPOSITORY === REPOSITORY, 'Unexpected repository');
  const api = createApi(process.env.GITHUB_TOKEN);
  if (command === 'plan') {
    const state = await currentState(api);
    const plan = makePlan(state.mainSha, state.pulls);
    output('plan', plan);
    output('matrix', { include: [plan.main, ...plan.previews] });
    output('main_sha', plan.main.sha);
  } else if (command === 'assemble') {
    const plan = validatePlan(JSON.parse(process.env.PREVIEW_PLAN || 'null'));
    const runId = process.env.GITHUB_RUN_ID, attempt = process.env.GITHUB_RUN_ATTEMPT;
    assert(/^[1-9][0-9]*$/.test(runId || '') && /^[1-9][0-9]*$/.test(attempt || ''), 'Invalid Actions run identity');
    assert(git(['rev-parse', 'HEAD'], path.resolve(__dirname, '..')) === plan.main.sha, 'Trusted checkout SHA mismatch');
    const [state, jobs] = await Promise.all([currentState(api),
      allPages(api, `/repos/${REPOSITORY}/actions/runs/${runId}/attempts/${attempt}/jobs`, 'jobs')]);
    const selected = selectPublishable(plan, state.mainSha, state.pulls, jobs);
    const manifest = await assemble(plan, selected);
    output('manifest', manifest);
    writeSummary(manifest);
  } else throw new Error('Usage: node scripts/publish-pages.cjs plan|assemble');
}

module.exports = { REPOSITORY, trustedPull, makePlan, validatePlan, testJobName,
  successfulTest, selectPublishable, createApi, allPages, currentState, checkoutSource,
  gitEnvironment, directoryBytes, SITE_BYTES_LIMIT, siteBase, writeIndex, assemble };
if (require.main === module) main(process.argv[2]).catch(error => {
  console.error(error.message);
  process.exitCode = 1;
});
